// ==UserScript==
// @name          Facebook Messanger Nice, Tidy and more responsive
// @namespace     http://userstyles.org
// @description	  Simple CSS that hides left toolbar from new Facebook Messenger (and open it on hover) and allow to make new chat a lot smaller
// @author        Krzychu
// @homepage      https://userstyles.org/styles/112567
// @include       https://www.messenger.com/*
// @include       http://www.messenger.com/*
// @run-at        document-start
// @version       0.20150418220911
// ==/UserScript==
(function() {var css = [ "* {\nfont-family: \"Ubuntu\" !important;\nfont-size: 16pt !important; \nline-height: 1 !important}",
        " ",

	"._1enh {",
	"  -webkit-transition: transform 0.4s ease-in-out, box-shadow 0.4s ease-in-out;",
	"-moz-transition: transform 0.4s ease-in-out, box-shadow 0.4s ease-in-out;",
	"-o-transition: transform 0.4s ease-in-out, box-shadow 0.4s ease-in-out;",
	"transition: transform 0.4s ease-in-out, box-shadow 0.4s ease-in-out;",
	"  position: relative;",
	"  z-index: 1000;",
	"  width: 320px !important;",
	"  margin-left: -250px;",
	"  background: white;",
	"  border-right: 1px solid rgba(0, 0, 0, .10);",
	"  transform: translate(1px);",
	"}",
	"  ",
	"._1enh:hover {",
	"  transform: translate(250px);",
	"  box-shadow:0 0 0 3000px rgba(0, 0, 0, .6);",
	"}",
	"",
	"._4sp8 { min-width: 320px; }",
	"",
        "._s15 {",
        "  height: 1px !important;", 
        "}",
        "",
        "._3rh8 {",
        "  height: 80px !important;", 
        "}",
        "",
        "._36ic {",
        "  height: 120px !important;", 
        "  padding-right: 28px !important;",
        "}",
        "",
        "._5742 {",
        "  height: 120px !important;", 
        "}",
        "",
        "._2fug {",
        "  transform: scale(2.2) !important;",  
        "}",
        "",
        "._4rv7 {",
        "  transform: scale(2.2) !important;",  
        "}",
        "",
        "._2oc8 {",
        "  transform: scale(2.2) !important;",  
        "}",
        "",
        "._31tl {",
        "  transform: scale(2.2) !important;",  
        "}",
        "",
        "._fl3 {",
        "  transform: scale(2.2) !important;",  
        "}",
        "",
        "._4rv6 {",
        "  transform: scale(2.2) !important;",  
        "}",
         "",
        "._4rv7 {",
        "  transform: scale(2.2) !important;",  
        "}",
        "",
        "._4rv9 {",
        "  transform: scale(2.2) !important;",  
        "}",
        "",
        "._yht {",
        "  transform: scale(2.2) !important;",  
        "}",
        "",
        "._5s2p {",
        "  width: 0px !important;",
        "  margin-right: 0px !important;",  
        "}",
        "",
        ".uiContextualLayer {",
        "  transform: scale(2.2) !important;", 
        "  margin-left: 140px !important;",
        "  margin-top: 140px !important;",  
        "  margin-bottom: 140px !important;",
        "  margin-right: 140px !important;",
        "}",
        "",
        "._53il {",
	" padding-top: 10px !important;", 
        "}",
        "",
        "._54ng {",
        "  font-size: 14pt !important;", 
        "}",
        "",
        "._vzk {",
        "  transform: scale(2.2) !important;",  
        "}",
        "",
        "._2oc8 {",
        "  margin-top: 20px !important;",
        "}",
        "",
        "._2fug {",
        "  margin-left: 20px !important;", 
        "  margin-top: 20px !important;",  
        "}",
        "",
        "._fl2 {",
        "  width: 260px !important;",  
        "  padding-left: 20px !important;",
        "  padding-bottom: 56px !important;",
        "  margin-rigth: 60px !important;",
        "}",
        "",
        "._fl2 li {",
	"  margin-right: 40px !important;",
        "}",
        "",
        "._1tqi {",
        "  font-size: 18pt !important;", 
        "}",
        "",
        "._3oh- {",
        "  font-size: 36pt !important;", 
        "}",
        "",
        "._kmc {",
        "  height: 100px !important;", 
        "}",
        "",
        "._2v6o {",
        "  font-size: 14pt !important;", 
        "}",
        "",
        "._4rv4 li {",
	"  margin-right: 40px !important;",
        "}",
        "",
        "._4rv4 {",
	" height: 100px !important;",
        " padding-top: 24px !important;", 
        "}",
        "",
        "._58al {",
        "  height: 60px !important;", 
        "  font-size: 13.5pt !important;",
        "}",
	"",
	"._1ht3 {",
	"  background-color: #CFE8FF !important;",
	"  }",


].join("\n");
if (typeof GM_addStyle != "undefined") {
	GM_addStyle(css);
} else if (typeof PRO_addStyle != "undefined") {
	PRO_addStyle(css);
} else if (typeof addStyle != "undefined") {
	addStyle(css);
} else {
	var node = document.createElement("style");
	node.type = "text/css";
	node.appendChild(document.createTextNode(css));
	var heads = document.getElementsByTagName("head");
	if (heads.length > 0) {
		heads[0].appendChild(node); 
	} else {
		// no head yet, stick it whereever
		document.documentElement.appendChild(node);
	}
}
})();

